modLoader="javafml" #mandatory
loaderVersion="${neoforge_loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${license}"
issueTrackerURL="https://github.com/FoundryMC/Veil/issues" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${version}" #mandatory
displayName="${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://docs.neoforged.net/docs/misc/updatechecker/)
displayURL="https://modrinth.com/project/veil" #optional
#logoFile="logo.png" #optional
credits="${credits}" #optional
authors="${mod_author}" #optional
description='''${description}'''

[[mixins]]
    config = "${mod_id}.mixins.json"
[[mixins]]
    config = "${mod_id}.neoforge.mixins.json"
[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[dependencies.veil]] #optional
    modId = "neoforge" #mandatory
    type = "required" #mandatory
    versionRange = "${neoforge_loader_version_range}" #mandatory
    ordering = "NONE"
    side = "BOTH"
[[dependencies.veil]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
[features.veil]
    openGLVersion = "[3.3,)"